### ISSUE TITLE
AltGr key won’t allow typing characters

### ISSUE THREAD

**Issue by UTF16** [hltj/wxMEdit#137]
Install anything but your default American English keyboard on Windows 7, like English UK keyboard. Open some typing application, like Notepad, and enable your English UK keyboard. Hold AltGr (Left Alt button) and press number 4 in the upper line of your letter keyboard. The Euro sign (€) will appear in Notepad or any other Windows text processor.

Now repeat the process in wxMedit. Nothing will appear.

English UK keyboard has some other AltGr characters that can be successfully typed in wxMedit (á, é), but they are not very usefull. But some other languages and keyboards are entirely based on the AltGr button (like Latvian). AltGr button is used to produce special characters in Latvian (ā, ņ, ģ etc.) and for some reason none of them work in wxMedit. You basically cannot type in any language that extensively uses the AltGr button, because some signs are not accessible. The Euro sign cannot be produced with any keyboard.

What makes me even more curious is that in text fields of the Options window works just fine – you can type whatever you want.

**Comment by hltj** [comment]
I will confirm later.

**Comment by hltj** [comment]
I fix this issue in the commit above.

Besizes, I've tested under Linux and found that AltGr was alreay support. There is a known issue that cannot input `€` with keybord layout "English(UK-intl-with-dead-key)" under Linux if wxMEdit built with wxGTK-3.0, while it work fine if built with wxGTK-2.8. It was caused by a bug of wxGTK-3.0.

**Comment by hltj** [comment]
The issue under Linux was also fixed!
