### ISSUE TITLE
Incorrect word  boundaries with non-English  characters (MadEdit/wxMEdit historical bug)

### ISSUE THREAD

**Issue by plzak** [hltj/wxMEdit#96]
When using certain accented letters in the text (like š, č, ř, ě, ů... my language is Czech), the editor treats them as "whitespace", or "end of word". This causes incorrect behaviour for functions like word-wrapping, moving cursor to the next word (ctrl-right_arrow, ctrl-left_arrow) etc.
The problem is the same for Windows-1250 and UTF-8 encodings. (I haven't tried others.)
wxMEdit version: v2.9.9
OS: LUbuntu 12.04.5
This is really a flaw of otherwise five-star editor... please fix it...
Thanks, Plzak

**Comment by hltj** [comment]
Got it. It was historical problem. It may be fixed at the next release.

**Comment by UTF16** [comment]
I even signed up here just because of this bug.

Yes, this is the only major problem with MadEdit since day 1 and every of its derivatives. Just because of this I cannot fully replace the otherwise awful Notepad. Since the application handles Japanese characters quite correctly, it makes the situation pretty awkward.

It concerns not only non-English letters, but also commas, full stops, colons, dashes etc. which makes functions like ctrl-right_arrow and ctrl-left_arrow annoyingly slow.

**Comment by hltj** [comment]
Sorry for delaying to the next release after the coming release for things were complex.

**Comment by hltj** [comment]
@plzak @UTF16 it will be fixed in 3.1.

**Comment by hltj** [comment]
original title: Problems with accented letters

While threre were not only problems with accented letters, but also problems with Chinese/Japanese/Lao characters etc.

e.g: **有些语言没有大写字母概念，比如中文。** should be splited as followed:
**有些** / **语言** / **没有** / **大写字母** / **概念** / **，** / **比如** / **中文** / **。**

**Comment by plzak** [comment]
Thanks for the info. I can't wait, that would be great! :)

**Comment by plzak** [comment]
Thank you very much for your effort! This fix is essential for me! :)
